examples/todo/src/objects/Todo__c.object
<CustomObject>
    <fields>
        <fullName>Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>The Text of the Todo</description>
        <label>Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Todo</label>
    <nameField>
        <displayFormat>T-{0000000000}</displayFormat>
        <label>Todo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Todos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

examples/shared/src/classes/TodoController.cls
global with sharing class TodoController {

    @auraEnabled
    global static List<Todo__c> getTodos() {
        List<Todo__c> todoList = [SELECT Id, Name, Completed__c, Text__c FROM Todo__c];
        return todoList;
    }

    @auraEnabled
    global static Todo__c updateTodo(Todo__c todo) {
        upsert todo;
        return todo;
    }

    @auraEnabled
    global static void completeTodo(Todo__c todo) {
        todo.Completed__c = !todo.Completed__c;
        update todo;
    }

    @auraEnabled
    global static void deleteTodo(Todo__c todo){
        delete todo;
    }

    @auraEnabled
    global static void completeAllTodos(Todo__c[] todos){
        for(Todo__c todo : todos){
            if(!todo.Completed__c){
                todo.Completed__c = true;
            }
        }

        update todos;
    }

    @auraEnabled
    global static void removeCompletedTodos(Todo__c[] todos){
        List<Todo__c> todosToBeDeleted = new List<Todo__c>();

        for(Todo__c todo : todos){
            if(todo.Completed__c){
                todosToBeDeleted.add(todo);
            }
        }

        delete todosToBeDeleted;
    }
}